baseURL = "https://bytethecookies.github.io/"
languageCode = "en"
title = "ByteTheCookies"
theme = "bytethecookies-theme"
defaultContentLanguage = "en"
enableEmoji = true
paginate = 5
enableGitInfo = true

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[outputs]
home = ["HTML", "RSS", "JSON"]


[params.categoryEmojis]
Web = "ğŸŒ"
Pwn = "ğŸ’»"
Crypto = "ğŸ”"
Forensic = "ğŸ•µï¸"
Osint = "ğŸ”"
Misc = "ğŸ”§"
Rev = "ğŸ”¨"
Block = "ğŸ”—"
