baseURL = "https://bytethecookies.github.io/"
languageCode = "en"
title = "ByteTheCookies"
description = "ByteTheCookies is a blog about ctf team, programming, and other tech-related topics."
theme = "bytethecookies-theme"
defaultContentLanguage = "en"
enableEmoji = true
paginate = 5
enableGitInfo = true

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[outputs]
home = ["HTML", "RSS", "JSON"]


[params.categoryEmojis]
Web = "ğŸŒ"
Netw = "ğŸ“¡"
Pwn = "ğŸ’»"
Crypto = "ğŸ”"
Forensic = "ğŸ•µï¸"
Osint = "ğŸ”"
Misc = "ğŸ”§"
Rev = "ğŸ”¨"
Block = "ğŸ”—"


[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]
[params]
  math = true