[[navbar]]
identifier = "about"
name = "About"
url = "/"
weight = 1
[[navbar]]
identifier = "news"
name = "News"
url = "/news/"
weight = 2
[[navbar]]
identifier = "writeups"
name = "Writeups"
url = "/writeups/"
weight = 3
[[navbar]]
identifier = "contacts"
name = "Contacts"
url = "/Contacts/"
weight = 4
